
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.cake]

		[types.cake.twilightdelight]
			aurora_cake = true
			torchberry_cake = true
			phytochemical_cake = true
			glacier_cake = true

		[types.cake.blue_skies]
			comet_berry_pie = true

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.cake.galospheric_delight]
			salted_caramel_cake = true

		[types.cake.mynethersdelight]
			magma_cake = true

		[types.cake.dungeonsdelight]
			monster_cake = true

	[types.wood_type]

		[types.wood_type.blue_skies]
			crystallized = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.betterarcheology]
			rotten = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.aether_redux]
			fieldsproot = true
			blightwillow = true
			cloudcap = true
			jellyshroom = true
			crystal = true
			glacia = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.endergetic]
			poise = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.sullysmod]
			petrified = true

		[types.wood_type.atmospheric]
			grimwood = true
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.wood_type.dungeonnowloading]
			azuro_oak = true

	[types.leaves_type]

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.blue_skies]
			crystallized = true
			crescent_fruit = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.aether]
			golden_oak = true
			holiday = true
			decorated_holiday = true
			crystal = true
			crystal_fruit = true
			skyroot = true

		[types.leaves_type.aether_redux]
			fieldsproot = true
			gilded_oak = true
			blighted_skyroot = true
			purple_glacia = true
			blightwillow = true
			glacia = true

		[types.leaves_type.deep_aether]
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.fruitsdelight]
			pear = true
			hawberry = true
			lychee = true
			mango = true
			persimmon = true
			peach = true
			orange = true
			apple = true
			mangosteen = true
			bayberry = true
			kiwi = true
			fig = true
			durian = true

		[types.leaves_type.twilightdelight]
			ironwood = true

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.autumnity]
			yellow_maple = true
			orange_maple = true
			red_maple = true
			maple = true

		[types.leaves_type.environmental]
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true
			cheerful_plum = true
			moody_plum = true
			hibiscus = true
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true
			palo_verde = true
			araucaria = true
			ripe_baobab = true
			flowering_baobab = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			ripe_orchard = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			yucca = true
			ripe_yucca = true
			flowering_yucca = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			silver_maple = true
			green_apple_skyris = true
			flowering_skyris = true
			flowering_ironwood = true
			white_sakura = true
			yellow_sakura = true
			yellow_birch = true
			yellow_spruce = true
			firecracker = true

		[types.leaves_type.dungeonnowloading]
			azuro = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			hollow_log = true
			vertical_slab = true

		[entries.wood_type.mcwbridges]
			rope_bridge = true
			rope_bridge_stair = true
			log_bridge_stair = true
			rail_bridge = true
			bridge_pier = true
			log_bridge_middle = true

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

